### ISSUE TITLE
界面调整 - 图表与边框的边距 - 透明模糊特效

### ISSUE THREAD

**Issue by GaoFeiGit** [25H/Maya#104]
原界面
![image](https://user-images.githubusercontent.com/31086787/112117964-de234080-8bf6-11eb-97c2-f0934b8e51ef.png)
期望的界面
![image](https://user-images.githubusercontent.com/31086787/112117911-d19ee800-8bf6-11eb-96f6-520a2f02032c.png)
其他的背景透明模糊特效
![image](https://user-images.githubusercontent.com/31086787/112120253-014eef80-8bf9-11eb-9b5b-11b9abb798ee.png)
![image](https://user-images.githubusercontent.com/31086787/112120583-5d197880-8bf9-11eb-99ed-704c0e04a4c6.png)

感谢作者开发如此优秀的软件，提一点小建议，希望能继续改进**Maya**。

**Comment by 25H** [comment]
项目边距：
```css
.list-icon-item {
    margin: 5px !important;
}

/*
 *  使用方法参考：https://blog.arae.cc/post/25838.html
 */
```

透明模糊，因maye使用前端开发实现不了
