### ISSUE TITLE
请问提示边框的ID是什么

### ISSUE THREAD

**Issue by zhouhuajdsh** [25H/Maya#108]
![QQ截图20210327062622](https://user-images.githubusercontent.com/29763911/112698799-6f2f3b80-8ec5-11eb-872e-9f9291067eba.jpg)
想把这边框改细一点

**Comment by 25H** [comment]
使用方法参照：https://blog.arae.cc/post/25838.html
```css
.list-icon {
    .list-icon-item {
        border-width: 5px !important;
    }
}
```
