### ISSUE TITLE
分类显示在顶部或者底部时，宽度不起作用，导致无法去掉边缘间隙

### ISSUE THREAD

**Issue by vac-ban** [25H/Maya#154]
![QQ图片20211123230618](https://user-images.githubusercontent.com/33921412/143049657-124f52e9-dadc-4b4c-8386-0c100b2d0625.png)

**Comment by 25H** [comment]
这个设置本身就不支持上下的，将下面的码加入到当前使用的皮肤文件内并重启就可以了

```css
.container.type-top,
.container.type-bottom {
	.list-tab-item {
		width: 20px !important;
	}
}
```
